"Resource/UI/replaybrowser/mainpanel.res"
{
	"CaratLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"CaratLabel"
		"font"			"HudFontSmallestBold"
		"labelText"		">>"
		"textAlignment"	"west"
		"xpos"			"85"
		"ypos"			"6"
		"zpos"			"10"
		"wide"			"20"
		"tall"			"15"
		"autoResize"	"1"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override" "200 80 60 255"
	}

	"HackTitleLabel"
	{
		"ControlName"	"CExLabel"
		"fieldName"		"HackTitleLabel"
		"font"			"HudFontSmallestBold"
		"labelText"		"REPLAYS AND MOVIES"
		"textAlignment"	"west"
		"xpos"			"100"
		"ypos"			"6"
		"zpos"			"10"
		"wide"			"200"
		"tall"			"15"
		"autoResize"	"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"fgcolor_override" "117 107 94 255"
	}
}